### ISSUE TITLE
How do I use Pixlr inside Brackets?

### ISSUE THREAD

**Issue by netsi1964** [dnbard/brackets-pixlr#1]
Hi,
I have installed your brackets pixlr extention, but how do I use it? I cannot find any menu points, no context menu so please write basic help here :-)

/Sten

**Comment by kallibee** [comment]
I'm on a MacBook pro, OS 10.12. Bracket 1.9 installed and all extensions updated.  I also have the blank spot where pixlr should appear and when I click it I get "adobe Flash player not installed" with a link to install it, which I did. Then I reloaded/restarted everything and still no icon. Bummer.

**Comment by kallibee** [comment]
But seeing as the issue persists 3 years later, double bummer.
